use GameMTBaseball
GO

--select * from dbo.tUserBattleBank where userdata = 0
select 'insert into dbo.tUserBattleBank(idx2, gameid, kakaonickname, trophy, tier, userdata, aniitemcode1, upcnt1, attstem1, defstem1, hpstem1, timestem1, aniitemcode2, upcnt2, attstem2, defstem2, hpstem2, timestem2, aniitemcode3, upcnt3, attstem3, defstem3, hpstem3, timestem3, treasure1, treasure2, treasure3, treasure4, treasure5, treasureupgrade1, treasureupgrade2, treasureupgrade3, treasureupgrade4, treasureupgrade5 )'
+ ' values('
+ ltrim(str(idx2)) + ', '
+ '''' + gameid + ''','
+ '''' + kakaonickname + ''','
+ ltrim(str(trophy)) + ', '
+ ltrim(str(tier)) + ', '
+ ltrim(str(userdata)) + ', '
+ ltrim(str(aniitemcode1)) + ', '
+ ltrim(str(upcnt1)) + ', '
+ ltrim(str(attstem1)) + ', '
+ ltrim(str(defstem1)) + ', '
+ ltrim(str(hpstem1)) + ', '
+ ltrim(str(timestem1)) + ', '
+ ltrim(str(aniitemcode2)) + ', '
+ ltrim(str(upcnt2)) + ', '
+ ltrim(str(attstem2)) + ', '
+ ltrim(str(defstem2)) + ', '
+ ltrim(str(hpstem2)) + ', '
+ ltrim(str(timestem2)) + ', '
+ ltrim(str(aniitemcode3)) + ', '
+ ltrim(str(upcnt3)) + ', '
+ ltrim(str(attstem3)) + ', '
+ ltrim(str(defstem3)) + ', '
+ ltrim(str(hpstem3)) + ', '
+ ltrim(str(timestem3)) + ', '
+ ltrim(str(treasure1)) + ', '
+ ltrim(str(treasure2)) + ', '
+ ltrim(str(treasure3)) + ', '
+ ltrim(str(treasure4)) + ', '
+ ltrim(str(treasure5)) + ', '
+ ltrim(str(treasureupgrade1)) + ', '
+ ltrim(str(treasureupgrade2)) + ', '
+ ltrim(str(treasureupgrade3)) + ', '
+ ltrim(str(treasureupgrade4)) + ', '
+ ltrim(str(treasureupgrade5)) + ')'
from dbo.tUserBattleBank where userdata = 0

